version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.1
    steps:
      - checkout
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.1
    steps:
      - checkout
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.1
    steps:
      - checkout
      - run: npm audit

workflow:
  wf:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test